### ISSUE TITLE
Error loading message color

### ISSUE THREAD

**Issue by Cardosu007** [M0RG4N01/Death-Messages-Remasterd#1]
I try to put the color code, but when I give rocket reload on the console the code disappears.

Sorry for my bad English.

**Comment by Alexr03** [comment]
Restart the server, don't rocket reload.

**Comment by M0RG4N01** [comment]
I just changed the colour this using these steps:
1. Went into config and changed colour to yellow
2. Went to console and typed ; "rocket reload"
3. Suicides on the server and the message colour was yellow

You must use colour names and not codes like "#FF0000"
Examples : "red" , "blue" , "green", "yellow" 

If that is what you're trying to do...

**Comment by Cardosu007** [comment]
Rocket reload for me did not work, only worked out when I restarted the server, whenever I gave rocket reload the color code fade from the configuration.

Thanks for creating the plugin, it was very good and simple to set up, thanks man!

**Comment by M0RG4N01** [comment]
Hmm, rocket reload seemed to work for me. However if you're able to get past the issue by restarting the server i guess thats okay.

Also thanks for the compliment 👍
