### ISSUE TITLE
Message Syntax

### ISSUE THREAD

**Issue by MythicalMithi** [M0RG4N01/Death-Messages-Remasterd#2]
I tried posting this in the comments but there is a pretty strict char limit. Thanks for the updates so far! All the features people want were added.  The messages would be much more concise if all them used the same variable order though.
[HP][Killer]>[action]>[victim]>{headshot?}>[weapon]>[distance]
[✙73]Morgan shot Mithi in the head with a Maplestrike from 120m
[✙73]Morgan slashed Mithi with a Machete

**Comment by pepixiko** [comment]
yes please

**Comment by khaiizha** [comment]
Add this please :D
Math.Round((double)Vector3.Distance(player.Position, killer.Position)).ToString();
