### ISSUE TITLE
Downloading .dll file

### ISSUE THREAD

**Issue by Eplen** [M0RG4N01/Death-Messages-Remasterd#20]
Hi, i am just a begginer in that thing, and i wanted to create a server for my friends, to play on it.

So, i am just asking, how can i install this to my server? I didnt found the .dll file, so i am not allowed to install it.

Is there any way, to do it? Please help.

**Comment by M0RG4N01** [comment]
Hello!

Here ya go: https://github.com/M0RG4N01/Death-Messages-Remasterd/raw/master/bin/Release/DeathMessagesRemastered.dll

**Comment by Eplen** [comment]
Thank you so much.
