### ISSUE TITLE
Error in death

### ISSUE THREAD

**Issue by Cardosu007** [M0RG4N01/Death-Messages-Remasterd#4]
The translation of death by player is wrong, type is the opposite in who killed, for example if I kill a player will appear that he killed me.

http://images.akamai.steamusercontent.com/ugc/140004481109717533/046C0DFACCEE770D001990A9E342539BB3914AA7/

**Comment by M0RG4N01** [comment]
You're not reading the text correctly,

The first one shows a death without headshot,
the second show a death with headshot.

You might be getting confused.

**Comment by Cardosu007** [comment]
I'm reading it correctly.
The player who killed is the one who dies and the one who died is what killed, it seems that something is wrong with the ID.
I already tried to test on another server, delete the plugin and the folder and install again, but it seems that the ID is the opposite.
